version: "3.4"
services:
  node-app:
    build: .
    ports:
      - 3000:3000
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - uploadly-app-data:/data/db
volumes:
  uploadly-app-data: